### ISSUE TITLE
Ninject and WebAPI 2

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#11]
I am having issues using ninject with WebAPI 2.

I created a webapi on my App but am having difficulty in using Ninject Dependency injection on the ApiController.

I have added Ninject.web.WebApi and Ninject.web.WebApi.WebHost, it didn't work out. I realised that the typical NinjectWebCommon.cs content was added using MrCMSKernel.cs. I tried creating another Ninjectdependencyresolver but it still didn't work out. Have anyone tried creating a webAPI2 on this CMS.

**Comment by gmstr** [comment]
Hi, we've done something with this when doing something on a project. We don't ship with it by default, because we don't use it out of the box, but you can create a simple IDependencyResolver instance as follows:

    using System.Web.Http.Dependencies;
    using Ninject;

    namespace MrCMS.Web.Apps.YourApp.API.IoC
    {
        public class NinjectDependencyResolver : NinjectDependencyScope, IDependencyResolver
        {
            private readonly IKernel _kernel;

            public NinjectDependencyResolver(IKernel kernel)
                : base(kernel)
            {
                _kernel = kernel;
            }

            public IDependencyScope BeginScope()
            {
                return new NinjectDependencyScope(_kernel.BeginBlock());
            }
        }
    }
Then wire it up in your app's RegisterServices function like so:

        protected override void RegisterServices(IKernel kernel)
        {
            GlobalConfiguration.Configure(configuration =>
            {
                configuration.DependencyResolver = new NinjectDependencyResolver(kernel);
            });
        }
using System.Web.Http's GlobalConfiguration class.

This seemed to work for me, but let me know if you have any bother, and I'll see if I can help.

**Comment by carlospence** [comment]
Thanks, It worked pretty good. I was pretty close to it but was registering the services at the wrong place.
