### ISSUE TITLE
Mr CMS ACL

### ISSUE THREAD

**Issue by carlospence** [MrCMS/MrCMS#13]
Goodday,
I need a brief explanation of the ACL and its rules so as to know how to apply them correctly.

**Comment by gmstr** [comment]
Hi, the basic idea of ACL (Access Control Levels) are that you can define actions that can take place within the system, and you can assign people in different roles to be able to have access or not have access to them. 

So if for some reason you had a role in your system that could view the user list in admin, but not add edit or delete it, you would create the two roles, then map the access rights in the ACL admin. The benefit of this is that you don't need to think about what roles can do what when defining the system, you just need to define the actions, the logic is then set up in admin by data.

To add a rule, just inherit from the ACLRule<T> class to assign it into your app's ACL, then just list out the operations. An example from the core would be user, which looks like this:

    public class UserACL : ACLRule
    {
        public const string View = "View";
        public const string Add = "Add";
        public const string Edit = "Edit";
        public const string Delete = "Delete";
        public const string SetPassword = "Set Password";
        public const string Roles = "Edit User Roles";

        public override string DisplayName
        {
            get { return "Users"; }
        }

        protected override List<string> GetOperations()
        {
            return new List<string> { View, Add, Edit, Delete, SetPassword, Roles };
        }
    }

I personally like to use constants so that you can use them easily in the controller attribute, so to limit the Users -> Add action, we just add the following attribute to the controller action:

        [HttpGet]
        [MrCMSACLRule(typeof(UserACL), UserACL.Add)]
        public PartialViewResult Add()
        {
            var model = new AddUserModel(); 
            ViewData["culture-options"] = _getUserCultureOptions.Get();
            return PartialView(model);
        }

Hope this makes sense. Let me know if you need anything clearing up.

**Comment by carlospence** [comment]
Thanks, I quite understand now.
