### ISSUE TITLE
How to add page templates ?

### ISSUE THREAD

**Issue by ghost** [MrCMS/MrCMS#33]
Hello,

When I want to add page template (ex. 2 or 3 columns) I found errors:

The "RenderBody" method has not been called for layout page "~/Apps/Core/Views/Shared/2col.cshtml".

Ok, I add RenderBody() on my 2col page:

```
@{
    Layout = "_BaseLayout.cshtml";
}
<div class="row">
    <div class="col-sm-8">@RenderBody()</div>
    <div class="col-sm-4">@{ RenderZone("Right Column"); }</div>
</div>`
```

So, I refresh and found this error:

The file "~/Apps/Core/Views/Shared/2col.cshtml" cannot be requested directly because it calls the "RenderBody" method.

Ho can I fix That?

Thanks per advances,

Yannick

**Comment by rbailo** [comment]
lets say you want to edit user account page to display 3 columns, Just add the areas in the admin section of the layout area of the page and add two columns, Then in your view place the code.
`<div class="row">
<div class="col-sm-4">@{ RenderZone("Left Column"); }</div>
    <div class="col-sm-8">@RenderBody()</div>
    <div class="col-sm-4">@{ RenderZone("Right Column"); }</div>
</div>`

Now you can go to your page layout and add content to the columns.

**Comment by yannickberthoud** [comment]
Hello,

But, if i want to create my own template with 3 columns ? First I create one html page with your previous code named threecolumns.cshtml and i publish them on \Apps\core\views\Shared\ folder.

After that, i create a layout, children of "base layout" with name "3 columns" and "threecolumns" for the file name.

when I save, I can add 2 "layout area" named Left column and Right column.

So, i can now add a page template named "3 columns", "text on 3 columns" for the "page view name" field. On page type i select "Text page (core)" and on layout combobox i select "3 columns", URL generator type is default and "single use" unchecked.

I select now page category and add on my root node a new page. on the list i select "3 columns" and give a name: "page with 3 columns".

I saved that and on the new view, i add a lorem ipsum on my wysiwyg editor.

I go on "Layout" tab and on the "Left column" i add a widget to area. I select "this page" on radiobox, widget type is a "text Wiget" and add on wysiwyg editor anoter "Left column lorem ipsum" text. His name's "Text on Left column". 

I repeat this previous operation for the right column. I save all, and click on publish now button. I click on view and found a 500 error.

Well, I go to find the log and found a bad view template name. I edit this one for the right name: "ThreeColumns". and go to clear cache on the right section. I back on my view and found another 500 error. Well, back to log and see:

The file "~/Apps/Core/Views/Shared/ThreeColumns.cshtml" cannot be requested directly because it calls the "RenderBody" method. 

I tried with this code:

`<div class="row">
<div class="col-sm-4">@{ RenderZone("Left Column"); }</div>
    <div class="col-sm-4">@RenderBody()</div>
    <div class="col-sm-4">@{ RenderZone("Right Column"); }</div>
</div>`

and with this code:

`@{
    Layout = "_BaseLayout";
 }`

<div class="row">
<div class="col-sm-4">@{ RenderZone("Left Column"); }</div>
    <div class="col-sm-4">@RenderBody()</div>
    <div class="col-sm-4">@{ RenderZone("Right Column"); }</div>
</div>.


But always the same error.

I make my operation on live so you can see exactly what I did.

**Comment by rbailo** [comment]
Are you using core or eCommerce? I will have to check that out.

**Comment by yannickberthoud** [comment]
heu... Web ? I opened your .sln on my visual studio and on web project i make a deploy. after that i transfered the files on my webserver and launch installation.

**Comment by rbailo** [comment]
this is not my project, i am just trying to help, MrCMS has 2 versions eCommerce version or basic MrCMS version. I do not think the owners of the project are actively monitoring this site as i haven't really seen a response from them.

**Comment by rbailo** [comment]
Posted by bill in one of the closed issues. [https://github.com/MrCMS/MrCMS/issues/21](https://github.com/MrCMS/MrCMS/issues/21).

Page templates allow you to reuse a page type / model but allow you to use a different view and/or layout and/or URL generator.

Say for example you wanted a new page called 'Home' which you were happy just using the TextPage page type you could create a new Page Template called 'Home'. When adding the Page template in the Page View Name field write the name of the view. For example HomePage - do not include the file extension. Make sure this view exists in your theme / app views folder.

The page type drop down would be set to TextPage and the layout/generator can just be defaulted. Single use means the new page template can only be used one time.

To use this new page you can do one of two things:

1) If the page already exists that you want to use this with, navigate to the edit screen for the page type and set it up the layout tab

2) If the page hasn't been added yet right click and add a page as you would normally, you will see "HomePage" is now an option to be added to the site.

**Comment by gmstr** [comment]
I hope @rbailo's reference of Will's previous answer was of use here. 

To try and summarise:
- Layouts are the structure of the page, leaving a "hole" for the page data (`RenderBody()`)
- Pages define what goes in the hole, and have a default implementation ([TextPage](https://github.com/MrCMS/MrCMS/blob/master/MrCMS.Web/Apps/Core/Pages/TextPage.cs) and [default .cshtml](https://github.com/MrCMS/MrCMS/blob/master/MrCMS.Web/Apps/Core/Views/Pages/TextPage.cshtml))
- Page templates take the data available in a page type, but will use a different .cshtml to present it.

So depending on what you want to do:
- If you want to change the structure of the page, you need a new layout
- If you want to show new data, you need a new page type
- If you want to show existing data in another way, you need a page template (You could also just make another page type with the same data. I got sick of doing this though, and hence implemented the templates)
