### ISSUE TITLE
Jquery Globalize is missing

### ISSUE THREAD

**Issue by JStika** [MrCMS/MrCMS#34]
Hi,

I'm download your MrCMS today.
All works, but (I switch locale to Slovak) and see Globalize is missing.
Where is?

**Comment by gmstr** [comment]
Hi, 

The localisations appear to be there for Slovak, but not Slovak (Slovakia) (https://github.com/MrCMS/MrCMS/blob/master/MrCMS.Web/Areas/Admin/Content/Scripts/lib/jquery/validate/localization/messages_sk.js and https://github.com/MrCMS/MrCMS/blob/master/MrCMS.Web/Areas/Admin/Content/Scripts/lib/jquery/ui/i18n/jquery.ui.datepicker-sk.js). 

This will be because we just echo all cultures as per the `CultureInfo.GetCultures(CultureTypes.AllCultures)` method, when allowing selection. This theoretically allows other languages to be supported that are outside of the initial i18n libraries, if needs be, by adding a file with the correct naming convention. This convention is also used when looking up files so Slovak is sk and Slovak (Slovakia) is sk_sk (I think). 

Hope this helps.

**Comment by JStika** [comment]
I kno, but in admin.js is e.g.: line 12

    Globalize.culture($("#CurrentUICulture").val());
    $.validator.methods.number = function (value, element) {
        return this.optional(element) ||
            !isNaN(Globalize.parseFloat(value));
    };

    $.validator.methods.date = function (value, element) {
        return this.optional(element) ||
            !isNaN(Globalize.parseDate(value));
    };

**Comment by gmstr** [comment]
If you've selected it in the settings, it should be getting used in the admin via that snippet you posted. a hidden input with the id CurrentUICulture is in the root template https://github.com/MrCMS/MrCMS/blob/master/MrCMS.Web/Areas/Admin/Views/Shared/_LayoutRoot.cshtml#L39 and should be getting set to the culture.
