### ISSUE TITLE
App Folder

### ISSUE THREAD

**Issue by Sourcenew** [MrCMS/MrCMS#77]
Why you don't change App folder name to Plugin?

i guess it is very better :)

**Comment by codeendevor** [comment]
I understand why, I believe it is Because the App folder is for your applications, Example would be that you would not have a web interface without the core application that uses the MrCMS lib for its functions. Plugins are more for an application that you create and place in the App folder to add functionality to your App, so if you wanted to add Plugins to the base download you would need to modify the core project to accept your plugins. Hope this helps.
